us_affiliate_id:
  type: string
  default: 0000000000
  description:
    en: Amazon US affiliate ID

uk_affiliate_id:
  type: string
  default: 0000000000
  description:
    en: Amazon Uk affiliate ID
    
affiliate_text:
  type: string
  default: As an Amazon Partner, this forum may be compensated if you make a purchase
  description:
    en: Disclaimer text
